:Author: brennorcs
:Email: brennorcs@poli.ufrj.br
:Date: 22/11/2017
:Revision: version#
:License: Public Domain

= Project: I2C_BLUETOOTH_MASTER-SLAVE

Código desenvolvido para Arduino Pro ou Pro Mini com o intuito de gerenciar 1 
dispositivo bluetooth para até 112 outros Arduinos Pro ou Pro Mini conectados
pelas portas SDA -Serial Data- e SCL -Serial Clock-. O protocolo de comunica-
ção entre os dispositivos utilizado é o I2C.
Os projeto é dividido em duas partes, contendo o código a ser utilizado no 
Master a fim de gerenciar o dispositivo bluetooth e o código a ser utilizado
no Slave. A implementação deste último trata-se apenas das funções de comuni-
cação e envio de dados, portanto fica ao usuário deste código a implementação
das funções desejadas sejam elas de sensoriamento ou outros para o dispositi-
vo Slave.
As funções de comunicação funcionam como eventos, interrompendo a execução do
código no Slave que será continuado posteriormente após enviar os dados.
O gerenciamento se dá por meio de uma variável Key contida em todos os Slaves.
Esta variável funciona similar a uma trava, entretanto de maneira diferente o
Master percorre todos os dispositivos Slaves verificando suas chaves a fim de
descobrir quem deseja enviar dados ou não. Caso os dados sejam transmitidos o
Arduino Slave suspende suas operações pela requisição do evento e envia 30byes
para o Arduino Master, o mesmo então envia byte a byte os dados para o dispo-
sitivo bluetooth.
Os 30bytes eviados pelo dispositivo Slave devems ser concatenados em e envia-
dos em uma string única;
Após checar a variável de controle -Key- e enviar ou nãos os dados para o mas-
ter se encaminha para o próximo dispositivo após um delay(500).

== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a public License.

=== Contributing
To contribute to this project please contact brennorcs <brennorcs@poli.ufrj.br>

=== BOM
2 or more Arduino Pro or pro Mini.
1 HC-06 bluetooth module.
Cable.


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
